import time
from copy import deepcopy


class MemoryStore:
    """
    Enterprise Memory Store

    Stores every memory generated by the agent.

    Features

    ✓ Session Memory
    ✓ Long-Term Memory
    ✓ Semantic Metadata
    ✓ Importance Score
    ✓ Timestamp
    ✓ Tags
    ✓ Fast Lookup
    ✓ Update/Delete
    """

    _memory = {}

    _next_id = 1

    # -----------------------------------------
    # Create
    # -----------------------------------------

    @classmethod
    def add(
        cls,
        conversation_id,
        content,
        memory_type="session",
        importance=50,
        tags=None,
        metadata=None,
    ):

        tags = tags or []

        metadata = metadata or {}

        memory = {

            "id": cls._next_id,

            "conversation_id": conversation_id,

            "content": content,

            "type": memory_type,

            "importance": importance,

            "tags": list(tags),

            "metadata": deepcopy(metadata),

            "created_at": time.time(),

            "updated_at": time.time(),

        }

        cls._memory.setdefault(
            conversation_id,
            [],
        ).append(memory)

        cls._next_id += 1

        return deepcopy(memory)

    # -----------------------------------------
    # Read
    # -----------------------------------------

    @classmethod
    def get(
        cls,
        conversation_id,
    ):

        return deepcopy(

            cls._memory.get(
                conversation_id,
                [],
            )

        )

    @classmethod
    def get_by_id(
        cls,
        conversation_id,
        memory_id,
    ):

        for memory in cls._memory.get(
            conversation_id,
            [],
        ):

            if memory["id"] == memory_id:

                return deepcopy(memory)

        return None

    # -----------------------------------------
    # Update
    # -----------------------------------------

    @classmethod
    def update(
        cls,
        conversation_id,
        memory_id,
        **fields,
    ):

        for memory in cls._memory.get(
            conversation_id,
            [],
        ):

            if memory["id"] == memory_id:

                for key, value in fields.items():

                    memory[key] = value

                memory["updated_at"] = time.time()

                return deepcopy(memory)

        return None

    # -----------------------------------------
    # Delete
    # -----------------------------------------

    @classmethod
    def delete(
        cls,
        conversation_id,
        memory_id,
    ):

        memories = cls._memory.get(
            conversation_id,
            [],
        )

        for i, memory in enumerate(memories):

            if memory["id"] == memory_id:

                memories.pop(i)

                return True

        return False

    # -----------------------------------------
    # Clear
    # -----------------------------------------

    @classmethod
    def clear(
        cls,
        conversation_id=None,
    ):

        if conversation_id is None:

            cls._memory.clear()

            cls._next_id = 1

        else:

            cls._memory.pop(
                conversation_id,
                None,
            )

    # -----------------------------------------
    # Search by Tag
    # -----------------------------------------

    @classmethod
    def by_tag(
        cls,
        conversation_id,
        tag,
    ):

        return [

            deepcopy(memory)

            for memory in cls._memory.get(
                conversation_id,
                [],
            )

            if tag in memory["tags"]

        ]

    # -----------------------------------------
    # Search by Type
    # -----------------------------------------

    @classmethod
    def by_type(
        cls,
        conversation_id,
        memory_type,
    ):

        return [

            deepcopy(memory)

            for memory in cls._memory.get(
                conversation_id,
                [],
            )

            if memory["type"] == memory_type

        ]

    # -----------------------------------------
    # Statistics
    # -----------------------------------------

    @classmethod
    def stats(
        cls,
    ):

        conversations = len(cls._memory)

        memories = sum(

            len(v)

            for v in cls._memory.values()

        )

        session = 0

        long_term = 0

        semantic = 0

        for items in cls._memory.values():

            for memory in items:

                t = memory["type"]

                if t == "session":

                    session += 1

                elif t == "long_term":

                    long_term += 1

                elif t == "semantic":

                    semantic += 1

        return {

            "conversations": conversations,

            "memories": memories,

            "session": session,

            "long_term": long_term,

            "semantic": semantic,

        }